image_model:
  model_name: "stabilityai/stable-diffusion-xl-base-1.0"
  generation_params:
    width: 240
    height: 240
  device: "cpu"

generation_model:
  model_name: "MTSAIR/Cotype-Nano"
  generation_params:
    max_new_tokens: 128
  device: "mps"