image_model:
  model_name: "runwayml/stable-diffusion-v1-5"
  generation_params:
    num_inference_steps: 20
  device: "cpu"

generation_model:
  model_name: "MTSAIR/Cotype-Nano"
  generation_params:
    max_new_tokens: 128
  device: "mps"