classification_model:
  model_name: "facebook/bart-large-mnli"
  classes: ['текст', 'картинка, изображение, нарисуй']
  device: "mps"

generation_model:
  model_name: "MTSAIR/Cotype-Nano"
  generation_params:
    max_new_tokens: 128
  device: "mps"